remote_theme: autodyne/pafe
url: https://nextzlog.dev
name: 無線部開発班
icon: /assets/head.png
lead: We provide amateur radio contest administration system ATS-4 and communication logging software zLog.
desc: アマチュア無線のコンテスト運営システムATS-4と交信記録ソフトzLogを提供します
items:
- name: ZyLO
  href: /zylo.html
- name: リアルタイムコンテスト
  href: /real.html
links:
- name:
  href: https://twitter.com/nextzlog
  icon: fab fa-twitter
- name: zLog
  href: https://zlog.org
- name: ALLJA1
  href: https://allja1.org
- name: 東大無線部
  href: https://ja1zlo.u-tokyo.org
jumps:
- name: autodyne
  href: https://github.com/autodyne
  icon: fab fa-github
- name: nextzlog
  href: https://github.com/nextzlog
  icon: fab fa-github
briefs:
  ats4: アマチュア無線のコンテストの集計作業を自動化。様々なコンテストに対応。楽しく開催できます。
  chpl: 型推論とテンプレートと区分化大域アドレス空間を特徴とした並列プログラミング言語の解説記事。
  dusk: 軽量スレッドによるタスク並列処理系を自作密行列積の速度を実測。高性能計算の基礎を学びます。
  fava: 関数型言語を自作。パーサコンビネータも型推論も仮想マシンも手作り。計算論の基礎を学びます。
  mine: 線型回帰からカーネル法まで。決定木から変分ベイズ法まで。機械学習の理論を実践的に学びます。
google_analytics: UA-75073167-1
plugins:
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- books
